name: Testing cookiecutter template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cookiecutter
    - name: Build and lint cookiecutter
      run: |
        cookiecutter --no-input . project_name=ci_project
    - name: Install cookiecutter template dependencies
      working-directory: ./ci_project
      run: |
        python -m pip install -r dev-requirements.txt
    - name: Install cookiecutter template dependencies
      working-directory: ./ci_project
      run: |
        python -m pip install -r dev-requirements.txt
    - name: Run pre-commit
      working-directory: ./ci_project
      run: |
        pre-commit validate-config
        pre-commit run --all-files
